<!DOCTYPE html>
<html>
<head>
    <title>Inquiry Report (PDF)</title>
    <style>
        body { font-family: sans-serif; }
        h2 { color: #333; }
        ul { list-style-type: none; padding: 0; }
        li { padding: 4px 0; }
    </style>
</head>
<body>
    <h2>Inquiry Report</h2>
    <ul>
        <li>Total Inquiries: {{ $totalInquiries }}</li>
        <li>Approved: {{ $approved }}</li>
        <li>Rejected: {{ $rejected }}</li>
    </ul>
    <p>Generated by MySebenarnya</p>
</body>
</html>
